name: Version Bump

on:
  push:
    tags:
      - 'v*'

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Update manifest version
      run: |
        cd Chrome_extension/src
        node -e "
          const fs = require('fs');
          const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
          manifest.version = '${{ steps.get_version.outputs.version }}';
          fs.writeFileSync('manifest.json', JSON.stringify(manifest, null, 2));
        "
        
    - name: Update package.json version
      run: |
        cd Chrome_extension/src
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.version = '${{ steps.get_version.outputs.version }}';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Chrome_extension/src/manifest.json Chrome_extension/src/package.json
        git commit -m "Bump version to ${{ steps.get_version.outputs.version }}" || exit 0
        git push